server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/proselyte_webflux_security
    username: andreyzakharenkov
    password:
  flyway:
    url: jdbc:postgresql://localhost:5432/proselyte_webflux_security
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iterator: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: proselyte

